### ISSUE TITLE
Authorization endpoint is changed to /par

### ISSUE THREAD

**Issue by cindy-chin** [eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift#24]
`      if let pushedAuthorizationRequestEndpoint = data.pushedAuthorizationRequestEndpoint, let url = URL(string: pushedAuthorizationRequestEndpoint) {
        self.authorizationEndpoint = url
      } else {
        throw ValidationError.error(reason: "In valid authorization endpoint")
      }`

Hiii, Is this expected in IssuanceAuthorizer to replace the authorizationEndpoint with /par?, I have some issue when trying with my issuer, but this seems abit weird to me.

**Comment by dtsiflit** [comment]
Thank you for finding this @cindy-chin , it's fixed and merged.
