### ISSUE TITLE
proof jwt is empty string

### ISSUE THREAD

**Issue by cindy-chin** [eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift#35]
Hi,
I have recently try out the authorization code flow in the mobile app. I found that, if there are now issuer, the iss field in proof jwt will be empty string.  from the specification, seems like only in pre-authorisation code flow can omit iss, even if iss is omitted, I not pretty sure if it should be empty string.

example
`{
  "iss": "",
  "aud": "
[https://e9b4-119-73-236-216.ngrok-free.app/oid4vci/test/test-issuer"](https://e9b4-119-73-236-216.ngrok-free.app/oid4vci/test/test-issuer%22)
,
  "iat": 1716947280,
  "nonce": "u76wqIVIFXwudmPYZwtE0N1xIRMKyVRX"
}`

Thank you, sorry for bothering so much

**Comment by dtsiflit** [comment]
Thank you @cindy-chin , we will look into this, no bother at all btw!
