### ISSUE TITLE
No access to SonarCloud Code Analysis details

### ISSUE THREAD

**Issue by srosenda** [eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift#73]
Merging of a PR #72 I authored results in a SonarCloud Code Analysis CI failure, see https://github.com/eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift/runs/28696395357. I would take a a look at the issues to fix them (or ignore, if appropriate), but I do not have access to the analysis details because it requires a SonarCloud account, which I do not have.

With the access issues resolved, would it make sense to run the analysis also in PR branches before merging them to avoid having to patch things with a new PR after merge?

**Comment by dtsiflit** [comment]
Hi @srosenda, no plans currently to grant access but we will resolve the sonar issue on our end. Thanks!
