### ISSUE TITLE
OpenId4VCIConfig.usePAR false seems to be ignored

### ISSUE THREAD

**Issue by avdwerff-ddy** [eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift#82]
It seems that when setting OpenId4VCIConfig.usePAR to false, the library still throws in AuthorizationServerClient with
```
if let pushedAuthorizationRequestEndpoint = data.pushedAuthorizationRequestEndpoint, let url = URL(string: pushedAuthorizationRequestEndpoint) { self.parEndpoint = url } else { throw ValidationError.error(reason: "In valid authorization endpoint") }
```

Shouldn't it be possible to completely skip this, so pushedAuthorizationRequestEndpoint can be nil in the Credential Offer?

Presuming PAR refers to:

```
  var authorizationServerSupportsPar: Bool {
    switch self {
    case .oidc(let metaData):
      return metaData.pushedAuthorizationRequestEndpoint != nil
    case .oauth(let metaData):
      return metaData.pushedAuthorizationRequestEndpoint != nil
    }
  }
```

**Comment by dtsiflit** [comment]
@avdwerff-ddy Thank you very much for submitting this!

There is now a [PR](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift/pull/83) that addresses this will be merged very soon.

**Comment by dtsiflit** [comment]
https://github.com/eu-digital-identity-wallet/eudi-lib-ios-wallet-kit/issues/83
This issue has been addressed here also.
