### ISSUE TITLE
OpenId is appended with scope value before making PAR request

### ISSUE THREAD

**Issue by pankaj-sp** [eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift#84]
**Description:**
In AuthorizationServerClient.swift at line number 197 openid is being appended as following:

`scope: scopes.map { $0.value }.joined(separator: " ").appending(" ").appending(Constants.OPENID_SCOPE),`

because of this when I tested the code I got scope value as "pid openid" which is not supported by all issuers.

Suggestion:
`scope: scopes.map { $0.value }.joined(separator: " "),`

Can I raise a pull request for this?

**Comment by dtsiflit** [comment]
Hello @pankaj-sp ,yes of course; please raise a PR.

**Comment by dtsiflit** [comment]
@pankaj-sp Thank you very much for your PR 🙂
