### ISSUE TITLE
CredentialIssuerId.init(from:) bypasses issuer id URL validation

### ISSUE THREAD

**Issue by srosenda** [eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift#93]
[`CredentialIssuerId.init(from:)`](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift/blob/1a1a8763117cb746477a4bdfe9c77adbb5241241/Sources/Entities/CredentialIssuer/CredentialIssuerId.swift#L43) decodes the credential issuer id as an `URL` and assigns it directly to `CredentialIssuerId.url`. This bypasses all validation performed by [`CredentialIssuerId.init(string:)`](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift/blob/1a1a8763117cb746477a4bdfe9c77adbb5241241/Sources/Entities/CredentialIssuer/CredentialIssuerId.swift#L21). See code references in the links above.

Suggested fix: call `CredentialIssuerId.init(string:)` from `CredentialIssuerId.init(from:)` instead of initialising the `URL` property directly.

**Comment by dtsiflit** [comment]
Nice catch @srosenda ! Assigning this issue to myself to address it.
