### ISSUE TITLE
AuthorizationServerMetadataResolver performs unnecessary fetches if the authorization server URL has path components

### ISSUE THREAD

**Issue by srosenda** [eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift#94]
Private functions [`AuthorizationServerMetadataResolver.fetchOIDCProviderMetadata`](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift/blob/1a1a8763117cb746477a4bdfe9c77adbb5241241/Sources/Main/Resolvers/CredentialOffer/AuthorizationServerMetadataResolver.swift#L74) and [`fetchAuthorizationServerMetadata`](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift/blob/1a1a8763117cb746477a4bdfe9c77adbb5241241/Sources/Main/Resolvers/CredentialOffer/AuthorizationServerMetadataResolver.swift#L110) perform unnecessary network requests if the authorization server URL has path components.

The [RFC8414 specification (that is also quoted in a comment in the code) states](https://www.rfc-editor.org/rfc/rfc8414.html#section-3) that the well-known path is _"formed by inserting a well-known URI string into the authorization server's issuer identifier between the host component and the path component, if any."_ The implementation first, contrary to the specification, appends the well-known path to the URI, attempts to fetch the metadata from the (incorrectly constructed) URL and if it fails, constructs the URL correctly by inserting the well-known path before the authorization server URL's path components. The code path that appends the path is unnecessary and should be removed. With it the local `modifyURL` extension can be removed too.

**Comment by dtsiflit** [comment]
Hello @srosenda, thank you for pointing this out. We acknowledge the issue and hope this will indeed be a temporary measure.

There are specific reasons behind this approach; for more details, please see this [comment](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/issues/224#issuecomment-2124863853), where we explain our rationale.

**Comment by srosenda** [comment]
> Hello @srosenda, thank you for pointing this out. We acknowledge the issue and hope this will indeed be a temporary measure.
> 
> There are specific reasons behind this approach; for more details, please see this [comment](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/issues/224#issuecomment-2124863853), where we explain our rationale.

OK, thanks for explaining this. A TODO or similar comment in the code would be good for cases like this. It could also be better that the implementation attempts the correctly formed URL first and have the incorrectly formed as the fallback?
