### ISSUE TITLE
Support Nonce in dPoP request header in token endpoint

### ISSUE THREAD

**Issue by dtsiflit** [eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift#95]
Add support for using dpopNonce provided by the authorization server, in the following interactions:

- When requesting access token (in the context of authorization code grant and / or pre-authorized code grant)
- When refreshing an access token (in the context of refresh grant).
- When pushing an authorization request to PAR endpoint.

In the above cases, the authorization server may reply with a (oauth2) error use_dpop_nonce either because the dopNonce is missing or because the the value it is not the correct.

Library catches the above error, updates the dpopNonce of the client, to the new value provided by the server and repeats the call using the new dpopNonce. At this stage, if authorization server replies again with a use_dpop_nonce, library will not retry again.

Furthermore, authorization server at any of the aforementioned three interactions may choose to update the dpopNonce.
To satisfy this, library evaluates whether success (200) responses contain a dpopNonce header, and if present, the locally held dpopNonce is updated.

[Authorization Server-Provided Nonce](https://datatracker.ietf.org/doc/html/rfc9449#name-authorization-server-provid) https://datatracker.ietf.org/doc/html/rfc9449#name-authorization-server-provid

[Resource Server-Provided Nonce](https://datatracker.ietf.org/doc/html/rfc9449#name-resource-server-provided-no)https://datatracker.ietf.org/doc/html/rfc9449#name-resource-server-provided-no

[Authorization Code Binding to a DPoP Key](https://datatracker.ietf.org/doc/html/rfc9449#name-authorization-code-binding-)https://datatracker.ietf.org/doc/html/rfc9449#name-authorization-code-binding-

**Comment by pankaj-sp** [comment]
Hi, Do we have any timeline for this?

**Comment by dtsiflit** [comment]
> I have already implemented this. Please let me know if I can raise a pull request for this.

Hello @pankaj-sp , yes feel free to raise a PR. Thanks!

**Comment by dtsiflit** [comment]
@pankaj-sp Just FYI we are working on this on our end.

**Comment by pankaj-sp** [comment]
Oh great, thanks for letting me know

**Comment by pankaj-sp** [comment]
Have you also implemented in wallet-kit? Is there any repo for wallet kit supporting dpNonce?

**Comment by dtsiflit** [comment]
This functionality will be handled internally within the VCI library. Wallet kit is not aware of this and will require no changes (except depending on the latest version of VCI of course :) )

**Comment by pankaj-sp** [comment]
Great thanks for answering

**Comment by pankaj-sp** [comment]
Hi, I am trying to use the library but getting following error: 
error : "use_dpop_nonce"
  ▿ errorDescription : Optional<String>
    - some : "nonce value missing"
  - cNonce : nil
  - cNonceExpiresInSeconds : nil
  - interval : nil

Can you please help me with this?

**Comment by dtsiflit** [comment]
Can you please share which request is giving you this error?

**Comment by pankaj-sp** [comment]
This happens when I am using following line of code: 
`let authorizedRequest = await issuer.authorizeWithAuthorizationCode(authorizationCode: request, authorizationDetailsInTokenRequest: nonceIncluded)` 
which ultimately uses `func requestAccessTokenAuthFlow(
    authorizationCode: String,
    codeVerifier: String,
    identifiers: [CredentialConfigurationIdentifier]
  ) async throws -> Result<(
    IssuanceAccessToken,
    CNonce?,
    AuthorizationDetailsIdentifiers?,
    TokenType?,
    Int?
  ), ValidationError>` in `AuthorizationServerClient`

**Comment by pankaj-sp** [comment]
I think I need to pass nonce to DPoPConstructor, but I am not able to pass it using the provided DPoPConstructorType protocol as it doesn't accept nonce.

**Comment by dtsiflit** [comment]
This method requestAccessTokenAuthFlow has a retry parameter (retry: Bool). If you set it to true the first time you call it, it should work.
If not, can you please open an issue in wallet kit to support dpop nonce?

**Comment by pankaj-sp** [comment]
Unfortunately I couldn't find it. I will raise an issue in wallet kit for this.
